name = "PiPiBochum"
uuid = "2a790af1-8976-4d5a-adc9-3981f32989e5"
authors = ["Alex Mikhasenko <aleksei.mikhasenko@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
LinearAlgebra = "1"
Parameters = "0.12.3"
